### ISSUE TITLE
Research on BCC

### ISSUE THREAD

**Issue by Torin-Perkins** [Torin-Perkins/revolutionizing-higher-ed-rankings#13]
Report the limitations (if any) that we need to consider with the BCC field (can we send 10,000 BCC's?)

**Comment by Torin-Perkins** [comment]
Outlook only allows 500 recipients per email. Can import the contacts from the csv files.

**Comment by aaronducote** [comment]
Outlook also only allows 1,000 recipients for 'non-relationship contacts', which includes the people receiving the surveys. Must split emails into work between different people over multiple days
