### ISSUE TITLE
Web Crawler for University Emails

### ISSUE THREAD

**Issue by aaronducote** [Torin-Perkins/revolutionizing-higher-ed-rankings#2]
Create a web crawler to crawl for contact information to send questionnaires to.

**Comment by Torin-Perkins** [comment]
I have pushed some code to the repo that should serve as a base for the web crawler, there is some more work to do to finish it completely

**Comment by Torin-Perkins** [comment]
Recently pushed code that will generate emails, gathering all the data now. It takes a while because we can only submit <1000 requests per hour before being flagged as a bot by google.

**Comment by Elliot-Foley** [comment]
CLI support and documentation added, marking as done
