### ISSUE TITLE
Add filter buttons to the website

### ISSUE THREAD

**Issue by Elliot-Foley** [Torin-Perkins/revolutionizing-higher-ed-rankings#21]
CSRankings has toggle buttons which will change the rankings based on if the specified topic should be included in the query.

First, make the HTML to support the buttons.
Then, use JS to connect them to the ranking system and work properly as filters.

**Comment by aaronducote** [comment]
Rhea installed the buttons to toggle each focus area.
Aaron added a select/deselect all button that allows the user to look at every focus area combined or none of the focus areas.
Marked as complete.
