### ISSUE TITLE
Send out emails

### ISSUE THREAD

**Issue by Elliot-Foley** [Torin-Perkins/revolutionizing-higher-ed-rankings#22]
Each person needs to send out emails, starting at their assigned letter. The letter assignments are the same as last time:
A-F: Aaron
G-L: Elliot
M-R: Rhea
Rest of the Alphabet: Torin

If the letters take different amounts of time, just communicate and we can split the work up differently if needed.

**Comment by Elliot-Foley** [comment]
Aaron and Elliot have made a document explaining the process to go from the CSV to emailing people: https://docs.google.com/document/d/1Cf-JaZcM358ZT2CRBVihWYD5o4ys0ljYUNuQJD3EYzU/edit?usp=sharing

**Comment by Elliot-Foley** [comment]
G-L are finished

**Comment by aaronducote** [comment]
A-F are finished
