### ISSUE TITLE
Test different methods for backtracing affiliations

### ISSUE THREAD

**Issue by Elliot-Foley** [Torin-Perkins/revolutionizing-higher-ed-rankings#25]
Inputs: our Google Forms-generated spreadsheet

Methods to test:
LLMs (Claude)
Google Scholar
CSrankings database search

Outputs:
Try to get them into our data a JSON or database format if possible, so we can be more flexible with how we adjust for multiple authors, multiple universities for a single author, authors with no affiliations. In particular, it should conform to the standard as defined in this ER diagram:
![Response Info](https://github.com/Torin-Perkins/revolutionizing-higher-ed-rankings/assets/130177938/99dddc50-9e59-4b39-9b85-810f53e55242)

So far, I have been using this JSON format, although alternative definitions could work as well.
`{
  "responses": [
    {
      "response": {
        "affiliation": "Example University",
        "interest": "Artificial Intelligence",
        "responses": [
          {
            "paper_name": "Example Paper 1",
            "researchers": [
              {
                "name": "John Doe",
                "affiliations": ["Example University"]
              },
              {
                "name": "Jane Smith",
                "affiliations": ["Another University"]
              }
            ]
          },
          {
            "paper_name": "Example Paper 2",
            "researchers": [
              {
                "name": "Alice Johnson",
                "affiliations": ["Example University"]
              },
              {
                "name": "Bob Williams",
                "affiliations": ["Yet Another University"]
              }
            ]
          }
        ]
      }
    },
    {
      "response": {
        "affiliation": "Another University",
        "interest": "Machine Learning",
        "responses": [
          {
            "paper_name": "ML Study",
            "researchers": [
              {
                "name": "Eva Brown",
                "affiliations": ["Another University"]
              },
              {
                "name": "Michael Green",
                "affiliations": ["Another University"]
              }
            ]
          }
        ]
      }
    }
  ]
}`

**Comment by aaronducote** [comment]
Currently trying out a few different methods:

Search Through CS Rankings CSV files
DOI search
ACM Search

Elliot is looking into CSV searching, Torin is looking into DOI searching, and Aaron is looking into ACM searching
